[package]
name = "scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bytemuck = "1.22.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
typetag = "0.2.20"
